stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t abernardo2/kubernetes-projeto2-dio:1.0 app/.
    - docker push abernardo2/kubernetes-projeto2-dio:1.0
